Issue7
EducationTraining/ETD_Back pull request #19
Opened 2019-12-20 14:19 UTC by Cndengzw

2019-12-20 14:45 UTC, yeiamx requested changes

2019-12-20 14:45 UTC, yeiamx commented on src/main/java/com/etd/etdservice/bean/users/response/ResponseGetStudent.java
> +		//response.setLastestTwoCourses();
为什么不设置LastestTwoCourses?还有就算你要注释//后面要跟一个空格

2019-12-20 14:45 UTC, yeiamx commented on src/main/java/com/etd/etdservice/bean/users/response/ResponseGetStudent.java
> +	public ResponseGetStudent(boolean success,String errMsg,Student bean){
逗号后面空格

2019-12-20 14:45 UTC, yeiamx commented on src/main/java/com/etd/etdservice/bean/users/response/ResponseGetStudent.java
> +		//response.setLastestTwoCourses(...);
同上， 而且这个构造方法的功能和fromBeanToResponse方法重复了，我们统一用fromBeanToResponse方法构造response。

2019-12-20 14:45 UTC, yeiamx commented on src/main/java/com/etd/etdservice/bean/users/response/ResponseGetStudent.java
> +	/*public static List<Course> setLastestTwoCourses(){
不需要的注释可以删掉

2019-12-20 14:45 UTC, yeiamx commented on src/main/java/com/etd/etdservice/bean/users/response/ResponseGetStudents.java
> +           this.studentsList=studentsList;
等号两边空格

2019-12-20 14:45 UTC, yeiamx commented on src/main/java/com/etd/etdservice/bean/users/response/ResponseGetStudents.java
> +    public ResponseGetStudents(boolean success, String errMsg,List<ResponseGetStudent> studentsList){
逗号后面空格

2019-12-20 14:45 UTC, yeiamx commented on src/main/java/com/etd/etdservice/serivce/impl/CourseServiceImpl.java
> +			return new BaseResponse(true,"");
逗号后面空格

2019-12-20 14:45 UTC, yeiamx commented on src/main/java/com/etd/etdservice/serivce/impl/CourseServiceImpl.java
> +			return new BaseResponse(false,"attendCourse failed");
逗号后面空格

2019-12-20 14:45 UTC, yeiamx commented on src/main/java/com/etd/etdservice/serivce/impl/CourseServiceImpl.java
> +		boolean status = courseStudentDAO.withdrawCourse(courseId,studentId);
逗号后面空格

2019-12-20 14:45 UTC, yeiamx commented on src/main/java/com/etd/etdservice/serivce/impl/CourseServiceImpl.java
> +			return new BaseResponse(true,"");
逗号后面空格

2019-12-20 14:45 UTC, yeiamx commented on src/main/java/com/etd/etdservice/serivce/impl/CourseServiceImpl.java
> +			return new BaseResponse(false,"withdrawCourse failed");
逗号后面空格

2019-12-20 14:45 UTC, yeiamx commented on src/main/java/com/etd/etdservice/serivce/impl/CourseServiceImpl.java
> +			return new ResponseIsAttendCourse(false, "param error",false);
逗号后面空格

2019-12-20 14:45 UTC, yeiamx commented on src/main/java/com/etd/etdservice/serivce/impl/CourseServiceImpl.java
> +		if(courseStudent !=null){
!=号右边空格

2019-12-20 14:45 UTC, yeiamx commented on src/main/java/com/etd/etdservice/serivce/impl/CourseServiceImpl.java
> +			return new ResponseIsAttendCourse(true,"",true);
逗号后面空格

2019-12-20 14:45 UTC, yeiamx commented on src/main/java/com/etd/etdservice/serivce/impl/CourseServiceImpl.java
> +			return new ResponseIsAttendCourse(true,"",false);
逗号后面空格

2019-12-20 14:45 UTC, yeiamx commented on src/main/java/com/etd/etdservice/serivce/impl/CourseServiceImpl.java
> +		//根据学生sessionKey获取学生id
//后面空格, 下同

2019-12-20 14:45 UTC, yeiamx commented on src/main/java/com/etd/etdservice/serivce/impl/CourseServiceImpl.java
> +			return new ResponseGetCourses(false, "param error",null);
逗号后面空格

2019-12-20 14:45 UTC, yeiamx commented on src/main/java/com/etd/etdservice/serivce/impl/CourseServiceImpl.java
> +		List<Integer> courseIdList = courseStudentDAO.queryCourseIdByStudentId(studentId);
DAO里新建一个queryCoursesByStudentId方法一步到位， 返回一个Course列表

2019-12-20 14:45 UTC, yeiamx commented on src/main/java/com/etd/etdservice/serivce/impl/CourseServiceImpl.java
> +			ResponseCourse rC = new ResponseCourse();
变量名写完整

2019-12-20 14:45 UTC, yeiamx commented on src/main/java/com/etd/etdservice/serivce/impl/CourseServiceImpl.java
> +		ResponseGetCourses attendedCourses = new ResponseGetCourses(true,"",responseCourses);
逗号后面空格

2019-12-20 14:45 UTC, yeiamx commented on src/main/java/com/etd/etdservice/serivce/impl/CourseServiceImpl.java
> +			return new ResponseGetStudents(false,"param error",null);
逗号后面空格

2019-12-20 14:45 UTC, yeiamx commented on src/main/java/com/etd/etdservice/serivce/impl/CourseServiceImpl.java
> +			 List<ResponseGetStudent> studentsList = new ArrayList<>();
开头多了一个空格

2019-12-20 14:45 UTC, yeiamx commented on src/main/java/com/etd/etdservice/serivce/impl/CourseServiceImpl.java
> +			return new ResponseGetStudents(true,"",studentsList);
逗号后面空格

2019-12-20 14:45 UTC, yeiamx commented on src/main/java/com/etd/etdservice/serivce/impl/CourseServiceImpl.java
> +			return new ResponseGetStudents(false,"courseId error",null);
逗号后面空格

2019-12-20 14:45 UTC, yeiamx commented on src/main/java/com/etd/etdservice/serivce/impl/CourseServiceImpl.java
> +				return new BaseResponse(true,"");
逗号后面空格 下同

2019-12-21 02:56 UTC, Cndengzw commented
已经完成规范格式及完善getAttendedStudents

2019-12-21 05:43 UTC, yeiamx approved these changes

2019-12-21 05:43 UTC, merged